### ISSUE TITLE
Handle .d2 files

### ISSUE THREAD

**Issue by Karreg** [landmaj/mkdocs-d2-plugin#1]
Hello,

I'm currently (and freshly) evaluating d2 as a replacement for drawio in our mkdocs documentations, as drawio is a bit overkill, and d2 looks promising, especially since I prefer the _-as-code_ logic.

Your plugin is working fine, and many thanks for that!

Still, I would be glad to see this plugin handle `.d2` files, alongside d2 markdown blocks. I have multiple reasons for that:

- the diagram may be used as a standalone diagram. As markdown block, it requires all the mkdocs galaxy to get the generated diagram
- people working on the diagram may be different than people working on the documentation
- a diagram could be included in multiples places

As example, I'm using the mkdocs drawio plugin that does exactly that. Of course there's a technical reason, drawio only handling its own format, but in the end it has been proven more effective than embedded diagram.

I have a sample mkdocs site, alongside an mkdocs devcontainer publicly available. I would be glad to discuss this need with you, if you are interested.

- [My devcontainer + mkdocs with drawio sample](https://gitlab.com/karreg/docker-mkdocs)
- [A branch to trial d2](https://gitlab.com/karreg/docker-mkdocs/-/tree/d2-trial?ref_type=heads)
- [Especially how diagrams are included](https://gitlab.com/karreg/docker-mkdocs/-/blob/d2-trial/docs/index.md?ref_type=heads&plain=1#L5)
- [The drawio plugin](https://github.com/LukeCarrier/mkdocs-drawio-exporter)

Thanks!

**Comment by Karreg** [comment]
I'm really glad that you like the idea :)

I had the same thought about configuration while writing this issue, and I got "eh, I guess it's doable directly in the D2 file, and if not, we could consider not allowing custom config for D2 file, while allowing on markdown diagrams".

But any other way to include them could work. I think there's a way to pass configuration to an include in a markeownish way, but without being markdown standard...

However, there's no markdown standard.

I'll give it a thought and come back with a better answer :)

**Comment by Karreg** [comment]
Got it. I knew I wouldn't have to search for long : https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment

Mkdocs material is using such key value configuration on images. We could consider the same thing... And even allow D2 configuration alongside image configuration when the diagram is generated.

**Comment by landmaj** [comment]
I got it working, you can check out and test version 0.4.1. I want to improve finding source files (https://github.com/landmaj/mkdocs-d2-plugin#known-issues-i-plan-to-fix) so I'm not closing the issue just yet.

**Comment by landmaj** [comment]
And it's done, I just released version 1.0.0. You can find usage and configuration examples in the [updated documentation](https://landmaj.github.io/mkdocs-d2-plugin/).

**Comment by Karreg** [comment]
Great! I'll try right away and get back to you...
Thanks!

**Comment by Karreg** [comment]
It's working fine. I have created a PR to fix typos in the associated documentation.

I'm interested by the _multiboard output cannot be written to stdout_ problem if you have more information, as I couldn't find reference to that in either d2 documentation nor their issue list. Do you know why it's (not) working like that, and if it can be worked around. The notion of scenario would be a great addition, by, for example, selecting the scenario to export by an include attribute...

**Comment by landmaj** [comment]
There is [this comment](https://github.com/terrastruct/d2/blob/451aa70fd68986c87b65b08e6c5785510d35c752/d2cli/main.go#L654) in D2 source code but no related issue, so I would not expect it to be fixed any time soon.

It doesn't allow outputting to stdout because such diagrams produce multiple files. Try to compile [last diagram from this page](https://d2lang.com/tour/composition/) like so:

```
d2 in.d2 out.svg
```

And will end up with the following output:

```
out
├── index.svg
└── numbers.svg
```

I have no idea how to embed that into HTML.

**Comment by Karreg** [comment]
scenarios could be used in 2 different manners:

- to generate a single, animated file, like what d2 is showcasing, but I'm not really impressed, I'm not sure about the use case. animation gets in the way of reading the diagram
- to generate the layer we want, to have a single diagram source, but multiple output depending on the location in the documentation. with an attribute, let's say `{ target="scenario_id }` for example.

I find the second use case more interesting. The only other way to do that, is to duplicate the diagram, just to display a bit more information. and it breaks the _only one golden source_ rule.

But I guess it still requires a fix on d2 side. Thanks for creating the #4 issue! :)
