### ISSUE TITLE
fence.py has a bug?

### ISSUE THREAD

**Issue by zuohuijun** [landmaj/mkdocs-d2-plugin#12]
I am working under Windows 10, and has installed D2. D2's version is 0.6.5

Python's version is 3.8.10 32bit.

when i start mkdocs server with 'python -m mkdocs serve', some error happened.

![image](https://github.com/landmaj/mkdocs-d2-plugin/assets/50851909/b5600131-f714-4a8f-a114-6b27f9490aef)
![image](https://github.com/landmaj/mkdocs-d2-plugin/assets/50851909/6696af12-d0d3-43ae-94c0-834f73e050af)

**Comment by landmaj** [comment]
I didn't notice I used some typing syntax not supported in older (but still supported) Python versions. This is fixed now in version `1.3.2`
