### ISSUE TITLE
Imports don't work

### ISSUE THREAD

**Issue by cloud-on-prem** [landmaj/mkdocs-d2-plugin#18]
For example, given this structure:

./src/_styles.d2

```d2
  style: {
    fill: "#f9f9f9"
    stroke: "#f9f9f9"
  }
```

./src/test.d2

```d2
...@_styles # Importing styles

test: {
  a -> b
}
```

When rendering the test.d2 file using:
`![Diagram](./src/test.d2)`

I see this error in the logs (and obviously no image is generated as a result)

```
| ERROR   -  mkdocs-d2-plugin: err: failed to compile -: -:1:1: failed to import "_styles.d2": open _styles.d2: no such file or directory
```

I am able to generate the image correctly using the command line (both svg and png)
```sh
d2 -l elk -s ./src/test.d2 test.svg
```

**Comment by kevgliss** [comment]
I'm also running into this limitation. D2, in particular, has a pretty strong import system, so I'd expect folks to be trying to leverage it.

**Comment by landmaj** [comment]
I released version 1.4.0 which supports imports in image tags. There is a caveat though, documented [here](https://landmaj.github.io/mkdocs-d2-plugin/guide/usage/#imports).

**Comment by landmaj** [comment]
BTW it don't think there is a way to make it work for fenced code blocks since such diagrams are passed using stdin. Setting CWD for subprocess does not appear to work, imports may just not work in d2 when using stdin.

**Comment by kevgliss** [comment]
Thank you @landmaj! I actually think it's likely a pretty reasonable trade-off not to have imports in fences, as I am far more likely to be building complex diagrams as standalone files and, hence, require imports.
